parameters:
#    yoxima_blog.example.class: yoxima\BlogBundle\Example

services:
#    yoxima_blog.example:
#        class: %yoxima_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    yoxima_blog.antispam:
        class: yoxima\BlogBundle\Antispam\YoximaAntispam
        arguments: [@mailer,%locale%,3]

    yoxima_blog.percentutil:
        class: yoxima\BlogBundle\PercentUtil\YoximaPercentUtil