<?php

namespace yoxima\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function myFindAll(){
        return $this->createQueryBuilder('a')
                ->getQuery()
                ->getResult();
        
    }
    
    public function findByTitle($word){
        return $this->createQueryBuilder('a')
                ->where('a.title like :title')
                ->setParameter('title',$word)
                ->getQuery()
                ->getResult();
    }
    
    public function getArticleAndComments(){
        return $this->createQueryBuilder('a')
                ->leftJoin('a.comments','c')
                ->addSelect('c')
                ->getQuery()
                ->getResult();
    }
    
    public function getWithCategories(array $categories_names){
        $qb = $this->createQueryBuilder('a');
                $qb->join('a.categories','cat')
                ->where($qb->expr()->in('cat.name', $categories_names));
        return $qb->getQuery()->getResult();
    }
}
